### ISSUE TITLE
CWE-310 - use of SHA1 in oauth.js

### ISSUE THREAD

**Issue by Phenomite** [cypress-io/request#3]
Using old crypto and causing firewall to block all of cypress due to this dependency.
Please see the sonar explanation below (specifically root cause).
You can see the 2 year old use of SHA1 all throughout that `lib\oauth.js` file.

### Explanation
The request package is vulnerable to Weak Authentication Algorithm. The function function in oauth.js uses SHA-1 for authentication which is no longer considered cryptographically secure. With enough resources an attacker might be able to crack the authentication mechanism and cause security attacks.

### Detection
The application is vulnerable by using this component.

### Recommendation
There is no non vulnerable version of this component/package. We recommend investigating alternative components or a potential mitigating control.

### Root Cause
request-2.88.5.tgz <= package/lib/oauth.js : [2.56.0 , )

**Comment by flotwig** [comment]
Thanks for the report. FYI - Cypress does not use the `oauth` functionality provided by this library, so since it does not represent a vulnerability in the way we use this library, we will probably not prioritize working on this. If there is already a fix open upstream we would be happy to merge it here.

**Comment by flotwig** [comment]
Or a PR to remove the oauth functionality would be fine.
